export const DOUBLE_QUOTE = '"';
export const SINGLE_QUOTE = "'";

export const DOUBLE_QUOTE_ENTITIES: Record<string, string> = {
  "&": "&amp;",
  [DOUBLE_QUOTE]: "&quot;",
};

export const SINGLE_QUOTE_ENTITIES: Record<string, string> = {
  "&": "&amp;",
  [SINGLE_QUOTE]: "&#39;",
};

export const VOID_ELEMENTS: Set<string> = new Set([
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
]);

export const BOOLEAN_ATTRIBUTES = new Set([
  "allowfullscreen",
  "async",
  "autofocus",
  "autoplay",
  "checked",
  "controls",
  "default",
  "defer",
  "disabled",
  "formnovalidate",
  "hidden",
  "ismap",
  "itemscope",
  "loop",
  "multiple",
  "muted",
  "nomodule",
  "novalidate",
  "open",
  "playsinline",
  "readonly",
  "required",
  "reversed",
  "selected",
]);

// CSS properties that don't need units
export const UNITLESS_PROPERTIES = new Set([
  "animationIterationCount",
  "aspectRatio",
  "borderImageOutset",
  "borderImageSlice",
  "borderImageWidth",
  "boxFlex",
  "boxFlexGroup",
  "boxOrdinalGroup",
  "columnCount",
  "flex",
  "flexGrow",
  "flexPositive",
  "flexShrink",
  "flexNegative",
  "flexOrder",
  "gridArea",
  "gridRow",
  "gridRowEnd",
  "gridRowSpan",
  "gridRowStart",
  "gridColumn",
  "gridColumnEnd",
  "gridColumnSpan",
  "gridColumnStart",
  "fontWeight",
  "lineClamp",
  "lineHeight",
  "opacity",
  "order",
  "orphans",
  "scale",
  "tabSize",
  "widows",
  "zIndex",
  "zoom",
]);

export const SVG_CAMEL_CASE_ATTRIBUTES = new Set([
  "viewBox",
  "gradientUnits",
  "gradientTransform",
  "patternUnits",
  "patternTransform",
  "preserveAspectRatio",
  "attributeName",
  "attributeType",
  "spreadMethod",
  "clipPathUnits",
  "maskUnits",
  "filterUnits",
  "primitiveUnits",
  "specularExponent",
  "limitingConeAngle",
  "markerUnits",
  "strokeMiterlimit",
  "baseProfile",
  "calcMode",
  "keyPoints",
  "keySplines",
  "keyTimes",
]);
