name: Deploy Website
on:
  push:
    branches: main
    paths:
      - website/**
  pull_request:
    branches: main
    paths:
      - website/**

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "reface"
          entrypoint: "./website/main.tsx"
