name: PR Check
on:
  pull_request:
    branches:
      - main
    paths:
      - "@reface/**"
      - "website/**"
jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: denoland/deno:latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Format Check
        id: format
        run: deno fmt --check

      - name: Check types
        id: types
        run: deno task check

      - name: Website – Check types
        id: website-types
        run: cd website && deno check ./

      - name: Run tests
        id: tests
        run: deno task test

      - name: Check publish
        if: steps.format.outcome == 'success' && steps.types.outcome == 'success' && steps.tests.outcome == 'success'
        run: deno publish --dry-run
